import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

def main():

    classy_filepath = r"C:\Users\drcla\OneDrive\Senior Honours Project\Extra Abundances\classyextras.csv"
    lzlcs_filepath = r"C:\Users\drcla\OneDrive\Senior Honours Project\Extra Abundances\lzlcsextras.csv"

    classy_mass = pd.read_csv(classy_filepath, delimiter=",", usecols = [0], header=0).to_numpy().flatten()
    classy_sfr = pd.read_csv(classy_filepath, delimiter=",", usecols = [1], header=0).to_numpy().flatten()
    classy_Z = pd.read_csv(classy_filepath, delimiter=",", usecols = [2], header=0).to_numpy().flatten()
    classy_Z_err_up = pd.read_csv(classy_filepath, delimiter=",", usecols = [3], header=0).to_numpy().flatten()
    classy_Z_err_down = pd.read_csv(classy_filepath, delimiter=",", usecols = [4], header=0).to_numpy().flatten()
    classy_S = pd.read_csv(classy_filepath, delimiter=",", usecols = [5], header=0).to_numpy().flatten()
    classy_S_err_up = pd.read_csv(classy_filepath, delimiter=",", usecols = [6], header=0).to_numpy().flatten()
    classy_S_err_down = pd.read_csv(classy_filepath, delimiter=",", usecols = [7], header=0).to_numpy().flatten()
    classy_Ar = pd.read_csv(classy_filepath, delimiter=",", usecols = [8], header=0).to_numpy().flatten()
    classy_Ar_err_up = pd.read_csv(classy_filepath, delimiter=",", usecols = [9], header=0).to_numpy().flatten()
    classy_Ar_err_down = pd.read_csv(classy_filepath, delimiter=",", usecols = [10], header=0).to_numpy().flatten()
    classy_Ne = pd.read_csv(classy_filepath, delimiter=",", usecols = [11], header=0).to_numpy().flatten()
    classy_Ne_err_up = pd.read_csv(classy_filepath, delimiter=",", usecols = [12], header=0).to_numpy().flatten()
    classy_Ne_err_down = pd.read_csv(classy_filepath, delimiter=",", usecols = [13], header=0).to_numpy().flatten()
    classy_Fe = pd.read_csv(classy_filepath, delimiter=",", usecols = [14], header=0).to_numpy().flatten()
    classy_Fe_err_up = pd.read_csv(classy_filepath, delimiter=",", usecols = [15], header=0).to_numpy().flatten()
    classy_Fe_err_down = pd.read_csv(classy_filepath, delimiter=",", usecols = [16], header=0).to_numpy().flatten()

    lzlcs_mass = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [0], header=0).to_numpy().flatten()
    lzlcs_mass_err = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [1], header=0).to_numpy().flatten()
    lzlcs_sfr = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [2], header=0).to_numpy().flatten()
    lzlcs_sfr_err = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [3], header=0).to_numpy().flatten()
    lzlcs_Z = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [4], header=0).to_numpy().flatten()
    lzlcs_Z_err_up = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [5], header=0).to_numpy().flatten()
    lzlcs_Z_err_down = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [6], header=0).to_numpy().flatten()
    lzlcs_Ne = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [7], header=0).to_numpy().flatten()
    lzlcs_Ne_err_up = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [8], header=0).to_numpy().flatten()
    lzlcs_Ne_err_down = pd.read_csv(lzlcs_filepath, delimiter=",", usecols = [9], header=0).to_numpy().flatten()

    classy_Z_err = np.stack((classy_Z_err_up, classy_Z_err_down), axis = 0)
    classy_S_err = np.stack((classy_S_err_up, classy_S_err_down), axis = 0)
    classy_Ar_err = np.stack((classy_Ar_err_up, classy_Ar_err_down), axis = 0)
    classy_Ne_err = np.stack((classy_Ne_err_up, classy_Ne_err_down), axis = 0)
    classy_Fe_err = np.stack((classy_Fe_err_up, classy_Fe_err_down), axis = 0)

    lzlcs_Z_err = np.stack((lzlcs_Z_err_up, lzlcs_Z_err_down), axis = 0)
    lzlcs_Ne_err = np.stack((lzlcs_Ne_err_up, lzlcs_Ne_err_down), axis = 0)

    plt.scatter(classy_Z, classy_S, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_Z, classy_S, xerr = classy_Z_err, yerr = classy_S_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$12 + log_{10}(O/H)$", fontsize = 12)
    plt.ylabel(r"$log_{10}(S/O)$", fontsize = 12)
    #plt.xlim(6.9, 9)
    #plt.ylim(-2, 0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig("SO-OH.png")
    plt.show()

    plt.scatter(classy_mass, classy_S, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_mass, classy_S, yerr = classy_S_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of total stellar mass in galaxy ($M_{\odot}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(S/O)$", fontsize = 12)
    #plt.xlim(5,11)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("SO-mass.png")
    plt.show()

    plt.scatter(classy_sfr, classy_S, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_sfr, classy_S, yerr = classy_S_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of star-formation rate in galaxy ($M_{\odot} yr^{-1}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(S/O)$", fontsize = 12)
    #plt.xlim(-3,3)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("SO-sfr.png")
    plt.show()

    plt.scatter(classy_Z, classy_Ar, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_Z, classy_Ar, xerr = classy_Z_err, yerr = classy_Ar_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$12 + log_{10}(O/H)$", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ar/O)$", fontsize = 12)
    #plt.xlim(6.9, 9)
    #plt.ylim(-2, 0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig("ArO-OH.png")
    plt.show()

    plt.scatter(classy_mass, classy_Ar, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_mass, classy_Ar, yerr = classy_Ar_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of total stellar mass in galaxy ($M_{\odot}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ar/O)$", fontsize = 12)
    #plt.xlim(5,11)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("ArO-mass.png")
    plt.show()

    plt.scatter(classy_sfr, classy_Ar, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_sfr, classy_Ar, yerr = classy_Ar_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of star-formation rate in galaxy ($M_{\odot} yr^{-1}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ar/O)$", fontsize = 12)
    #plt.xlim(-3,3)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("ArO-sfr.png")
    plt.show()

    plt.scatter(classy_Z, classy_Ne, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_Z, classy_Ne, xerr = classy_Z_err, yerr = classy_Ne_err, fmt = "none", ecolor = "slateblue")
    plt.scatter(lzlcs_Z, lzlcs_Ne, s = 20, ls = "", color = "salmon", label = "LzLCS")
    plt.errorbar(lzlcs_Z, lzlcs_Ne, xerr = lzlcs_Z_err, yerr = lzlcs_Ne_err, fmt = "none", ecolor = "salmon")
    plt.xlabel(r"$12 + log_{10}(O/H)$", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ne/O)$", fontsize = 12)
    #plt.xlim(6.9, 9)
    #plt.ylim(-2, 0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig("NeO-OH.png")
    plt.show()

    plt.scatter(classy_mass, classy_Ne, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_mass, classy_Ne, yerr = classy_Ne_err, fmt = "none", ecolor = "slateblue")
    plt.scatter(lzlcs_mass, lzlcs_Ne, s = 20, ls = "", color = "salmon", label = "LzLCS")
    plt.errorbar(lzlcs_mass, lzlcs_Ne, xerr = lzlcs_mass_err, yerr = lzlcs_Ne_err, fmt = "none", ecolor = "salmon")
    plt.xlabel(r"$log_{10}$ of total stellar mass in galaxy ($M_{\odot}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ne/O)$", fontsize = 12)
    #plt.xlim(5,11)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("NeO-mass.png")
    plt.show()

    plt.scatter(classy_sfr, classy_Ne, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_sfr, classy_Ne, yerr = classy_Ne_err, fmt = "none", ecolor = "slateblue")
    plt.scatter(lzlcs_sfr, lzlcs_Ne, s = 20, ls = "", color = "salmon", label = "LzLCS")
    plt.errorbar(lzlcs_sfr, lzlcs_Ne, xerr = lzlcs_sfr_err, yerr = lzlcs_Ne_err, fmt = "none", ecolor = "salmon")
    plt.xlabel(r"$log_{10}$ of star-formation rate in galaxy ($M_{\odot} yr^{-1}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Ne/O)$", fontsize = 12)
    #plt.xlim(-3,3)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("NeO-sfr.png")
    plt.show()

    plt.scatter(classy_Z, classy_Fe, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_Z, classy_Fe, xerr = classy_Z_err, yerr = classy_Fe_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$12 + log_{10}(O/H)$", fontsize = 12)
    plt.ylabel(r"$log_{10}(Fe/O)$", fontsize = 12)
    #plt.xlim(6.9, 9)
    #plt.ylim(-2, 0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig("FeO-OH.png")
    plt.show()

    plt.scatter(classy_mass, classy_Fe, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_mass, classy_Fe, yerr = classy_Fe_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of total stellar mass in galaxy ($M_{\odot}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Fe/O)$", fontsize = 12)
    #plt.xlim(5,11)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("FeO-mass.png")
    plt.show()

    plt.scatter(classy_sfr, classy_Fe, s = 20, ls = "", color = "slateblue", label = "CLASSY")
    plt.errorbar(classy_sfr, classy_Fe, yerr = classy_Fe_err, fmt = "none", ecolor = "slateblue")
    plt.xlabel(r"$log_{10}$ of star-formation rate in galaxy ($M_{\odot} yr^{-1}$)", fontsize = 12)
    plt.ylabel(r"$log_{10}(Fe/O)$", fontsize = 12)
    #plt.xlim(-3,3)
    #plt.ylim(-2.2, -0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("FeO-sfr.png")
    plt.show()


main()






